### ISSUE TITLE
add cff file

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/book-of-n3c-v1#15]
When I created a release (#13) and checked Zenodo, I noticed its advice about cff files.  It has some useful information, including these two paragraphs:

https://citation-file-format.github.io/

>CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.
>
>This is an example of a simple CITATION.cff file:

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/0000-0003-4925-7248
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```

>When you have a CITATION.cff file in your GitHub repository, make a release and publish it on Zenodo via the Zenodo-GitHub integration, Zenodo will use the citation information you’ve provided to populate the publication entry! This makes it easier for software developers and maintainers to publish their software with complete and correct metadata.

The [readme](https://github.com/citation-file-format/citation-file-format#readme) and [schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)  have a lot more details.
